### PR TITLE
[PLT-12] add streaming

### PR DESCRIPTION
**Pull request by clementou**
https://github.com/cmu-dsc/poker-engine-2025/issues/20

Add streaming of logs via GraphQL subscriptions. I tried other solutions but they won't work for our usecase.

Also includes fixes to the match function.

I tested the query works but can't get the websocket connection working. It'll be easier to test this when there's a working frontend to develop on.

### CODE REVIEW

**Review by almutwakel — APPROVED** [review]
lgtm
going forward please attach actual logging of tests in the PR when possible

**Comment by clementou** [comment]
@sirtobsi 

do you think it would be useful to change the `isCompleted` field in `MatchDao` to an enum like this?

```
enum MatchStatus {
  NOT_STARTED
  IN_PROGRESS
  COMPLETED
}

model MatchDao {
  matchId        Int              @id @unique @default(autoincrement())
  timestamp      DateTime         @default(now())
  teamMatches    TeamMatchDao[]
  status         MatchStatus      @default(NOT_STARTED)
  matchRequest   MatchRequestDao? @relation(fields: [matchRequestId], references: [id])
  matchRequestId Int?             @unique
}
```

**Comment by sirtobsi** [comment]
@clementou  when is a match in the db, but not started? If that can happen, it would be useful…

**Comment by clementou** [comment]
@sirtobsi I'm considering using Fargate Spot to run matches. If there's no Spot capacity available when a match is created (like through request), we might want to let the user know their match was created, but can't be run yet.

**Comment by sirtobsi** [comment]
> @sirtobsi I'm considering using Fargate Spot to run matches. If there's no Spot capacity available when a match is created (like through request), we might want to let the user know their match was created, but can't be run yet.

ok, I can add it. I plan on working a bit more tonight or on friday. I will add these changes as well.

**Pull request merged**
