### PR TITLE
[PLT-??] Switch the match to Fargate

### PR DESCRIPTION
**Pull request by clementou**
Spot Fargate with ARM (~0.3 cents per match) is cheaper than Lambda (~4-6 cents per match).

### CODE REVIEW

**Review by sirtobsi — COMMENTED** [review]
Does it include both the auth and the changes for fargate? Very big diff :(

**Comment by clementou** [comment]
O this is branched off the auth PR, let's review that first

**Comment by dongkyunk** [comment]
Isn't fargate better for something that runs persistently? Lambda is better for small single-function jobs like our poker match.

**Comment by clementou** [comment]
I think this is too long for lambda, lambda is better for things that take like <5 seconds to run, otherwise you should use step-functions.

Main concern is the cost is much higher for lambda.

We can test both before merging this to see if there are any pitfalls I missed.

**Comment by clementou** [comment]
price per 15 min match on arm is
lambda: $0.0480
fargate spot: $0.0036
ec2 spot: $0.0013

**Pull request merged**
